### ISSUE TITLE
Kanban Board Review

### ISSUE THREAD

**Issue by ram1117** [ram1117/recipe-app#11]
Hi, We are a team of two members, me @ram1117 and @Lancelot-SO . We have created the Kanban board and created tasks based on project requirements. We have assigned tasks to ourselves. Please review and provide feedback on the Kanban setup.

[Our Kanban board](https://github.com/ram1117/recipe-app/projects/1)

**Comment by OyePriscilla** [comment]
Hi @ram1117 and @Lancelot-SO 👏 👏, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Set up kanbanboard ✔️ 
Detailed issues description ✔️ 

## Required Changes ♻️

- [ ] Please kindly ensure that each project requirement has corresponding task in the kanban board, I observed that you did totally follow the project requirement strictly. 👍 **I think doing this will make you kanban board more informative.**

<img width="798" alt="Untitled" src="https://github.com/ram1117/recipe-app/assets/103386183/0a5e1b16-84e0-49d7-836f-b22b58f06e4e">



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ram1117** [comment]
Hi, I have changed the task details based on the tasks listed in the project requirements. Please review and provide feedback.

[Our Kanban board](https://github.com/ram1117/recipe-app/projects/1)

**Comment by mckent05** [comment]
Hi guys, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![almost there](https://user-images.githubusercontent.com/73607512/207265397-5ef597f5-a50c-49b4-8f07-7548b0520e98.gif)


 ## Highlights
- All tasks have been properly assigned✔️ ✔️ 
- Kanban board has been rightly seup 👍 👍 


 ## Required Changes ♻️
- Good job changing the task details based on tasks listed in the project requirements, but according to the project requirements ` Each requirement should have at least one corresponding card in the Kanban board`, this project task `Make sure there are no N+1 queries happening` is missing in your Kanban board, please fix this 🙏 
_Check the comments under the review._

## Optional suggestions

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your code.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ram1117** [comment]
Added a new task for N+1 queries.

 [1pt] - (#Group Task) - Ensure there are no N+1 queries in the project. #13

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @ram1117 and @Lancelot-SO,

✔️ Tasks are complete and well assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
